# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataType', models.CharField(max_length=10)),
                ('attrName', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='EnumDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrName', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='EnumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=75)),
                ('enumDataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.EnumDataType')),
            ],
        ),
        migrations.CreateModel(
            name='RiskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='enumdatatype',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.RiskModel'),
        ),
        migrations.AddField(
            model_name='basicdatatype',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.RiskModel'),
        ),
    ]
