# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdatatype',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basics', to='restapi.RiskModel'),
        ),
        migrations.AlterField(
            model_name='enumdatatype',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enums', to='restapi.RiskModel'),
        ),
        migrations.AlterField(
            model_name='enumoption',
            name='enumDataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restapi.EnumDataType'),
        ),
    ]
